version: '3'
services:
  db:
    image: mariadb:10.2
    volumes:
      - "./data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: datapw

  redis:
    image: redis:3.2-alpine

  nginx:
    image: nginx:alpine
    links:
      - fpm:fpm
    ports:
      - 80:80
    volumes:
      - "../blog:/var/www/html"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    environment:
        WEBROOT: "/var/www/html"

  fpm:
    image: php:7.0-fpm
    links:
      - db:db
      - redis:redis
    volumes:
      - "../blog:/var/www/html"
      - "./config/php.ini:/usr/local/etc/php/php.ini"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      PMA_USER: blog
      PMA_PASSWORD: datapw
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: datapw
